// <auto-generated />
namespace HospitalAppointment.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class New_fields_for_passwords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New_fields_for_passwords));
        
        string IMigrationMetadata.Id
        {
            get { return "201703021510056_New_fields_for_passwords"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
