//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskStatusHistory
    {
        public System.Guid TSHId { get; set; }
        public System.Guid TaskId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string ChangeComments { get; set; }
        public System.Guid UsersId { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Task Task { get; set; }
        public virtual TaskUser TaskUser { get; set; }
    }
}
