//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAssignHistory
    {
        public System.Guid TAHId { get; set; }
        public System.Guid TaskAssignId { get; set; }
        public System.Guid UserId { get; set; }
        public string Comments { get; set; }
        public int StatusId { get; set; }
        public System.DateTime AssignDate { get; set; }
        public System.DateTime CloseDate { get; set; }
        public System.DateTime ChangeDate { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual TaskAssign TaskAssign { get; set; }
        public virtual TaskUser TaskUser { get; set; }
    }
}
